### ISSUE TITLE
This implementation is fragile

### ISSUE THREAD

**Issue by hunger** [OneMoreGres/qtc-paneencode#1]
There is no guarantee that the activeTarget is the one that a project is currently trying to build. This will make you connect to the wrong build steps occasionally.

The only thing to make this work reliably is to integrate this into Qt Creator proper. Maybe you could consider to contribute such a functionality?

**Comment by OneMoreGres** [comment]
Looks like fixed. Now connecting only to targets/configurations that are really being built.
Anyway such plugin can't be 100% reliable because: 
- automatic charset detection is not enough precise
- and manual charset setting:
  - will affect QTC's own messages (not critical, but..)
  - will not work if tool (or set of tools) got output in different encodings.

So this plugin is more a trick than a solution.

**Comment by hunger** [comment]
Yes, this is a really annoying problem on Windows boxes. All the other OSes
use UTF8 encoding anyway:-)
